version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login -u mridhulimpress -p q1w2e3

     # build the application image
     - run: docker build -t mridhulimpress/clairscanner:latest .

     # deploy the image
     - run: docker push mridhulimpress/clairscanner:latest
